grails-app/controllers/mystore/HomeController.groovy
package mystore

import grails.plugin.springsecurity.annotation.Secured

class HomeController {

    def productService
    static def allowedMethods = [store: "POST"]

    def index() {
        def products = Product.findAllByIsPublishedAndSaleDateLessThan(true, new Date())
        render(view: "index", model: [products: products])
    }

    @Secured(["ROLE_USER", "ROLE_ADMIN"])
    def create() {
        render(view: "create", model: [product: new Product()])
    }

    @Secured(["ROLE_USER", "ROLE_ADMIN"])
    def store(Product product) {
        withForm {
            def error = productService.saveProduct(product)
            if (error == "")
                redirect(action: "show", params: [id: product.id])
            else
                render(view: "create", model: [error: error])
        }.invalidToken {
            render(view: "index", model: [error: "ERROR : Invalid Token !"])
        }
    }

    def show(Product product) {
//        CHECK IF CURRENT USER == PRODUCT.ADDED_BY
//            SHOW PRODUCT DETAIL EVEN IF IT'S NOT PUBLISHED
        if(product.isPublished)
            render(view: "show", model: [product: product])
        else
            render(view: "invalid")
    }

    @Secured(["ROLE_USER", "ROLE_ADMIN"])
    def edit(Product product) {
//        CHECK IF CURRENT USER == PRODUCT.ADDED_BY
        render(view: "edit", model: [product: product])
    }

    @Secured(["ROLE_USER", "ROLE_ADMIN"])
    def update(Product product) {
        withForm {
            def error = productService.saveProduct(product)
            if (error == "")
                redirect(action: "show", params: [id: product.id])
            else
                render(view: "edit", model: [product: product, error: error])
        }.invalidToken {
            render(view: "index", model: [error: "ERROR : Invalid Token !"])
        }
    }

    def init() {
        def user = User.findAllByUsername("admin")
        def role = Role.findAllByAuthority("ROLE_ADMIN")
        def role_u = Role.findAllByAuthority("ROLE_USER")
        User user_admin = new User(username: "admin", password: "admin", enabled: true)
        Role role_admin = new Role(authority: "ROLE_ADMIN")
        Role role_user = new Role(authority: "ROLE_USER")
        if(user.size() == 0)
            user_admin.save(flush: true)
        if(role.size() == 0) {
            role_admin.save(flush: true)
            UserRole.create(user_admin, role_admin)
        }
        if(role_u.size() == 0)
            role_user.save(flush: true)
        redirect(action: "index")
    }

}

grails-app/views/home/create.gsp
<!DOCTYPE HTML>
    <html>
    <head>
        <meta name="layout" content="main" />
        <title>Create Product | Simple Online Store</title>
    </head>

    <body>
        <h1>Create Product</h1>
        <p>${error}</p>
        <g:form action="store" useToken="true">
            <label name="name">Product Name:</label>
            <g:textField name="name"></g:textField>
            <br>
            <label name="description">Description:</label>
            <g:textArea name="description"></g:textArea>
            <br>
            <label name="salePrice">Sales Price:</label>
            <g:textField name="salePrice"></g:textField>
            <br>
            <label name="saleDate">Sales Date:</label>
            <g:datePicker name="saleDate" precision="day"></g:datePicker>
            <br>
            <label name="isPublished">Published</label>
            <g:checkBox name="isPublished"></g:checkBox>
            <br>
            <g:submitButton name="submit" value="Add Product"></g:submitButton>
        </g:form>
    </body>
</html>

grails-app/views/home/edit.gsp
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>Edit ${product.name} | Simple Online Store</title>
    </head>

    <body>
        <h1>Edit : ${product.name}</h1>
        <p>${error}</p>
        <g:form action="store" useToken="true">
            <g:hiddenField name="id" value="${product.id}"></g:hiddenField>
            <label name="name">Product Name:</label>
            <g:textField name="name" value="${product.name}"></g:textField>
            <br>
            <label name="description">Description:</label>
            <g:textArea name="description" value="${product.description}"></g:textArea>
            <br>
            <label name="salePrice">Sales Price:</label>
            <g:textField name="salePrice" value="${product.salePrice}"></g:textField>
            <br>
            <label name="saleDate">Sales Date:</label>
            <g:datePicker name="saleDate" precision="day" value="${product.saleDate}"></g:datePicker>
            <br>
            <label name="isPublished">Published</label>
            <g:checkBox name="isPublished" value="${product.isPublished}"></g:checkBox>
            <br>
            <g:submitButton name="submit" value="Edit Product"></g:submitButton>
        </g:form>
    </body>
</html>

grails-app/views/home/index.gsp
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>Simple Online Store</title>
    </head>

    <body>
    %{-- IF not login --}%
        <sec:ifNotLoggedIn>
    %{--    Login Form --}%
            <g:link controller='login' action='auth'>Login</g:link><br>
        </sec:ifNotLoggedIn>
        <sec:ifLoggedIn>
            <h3>Welcome, <sec:loggedInUserInfo field="username"/></h3>
            <g:link controller='logoff'>Logout</g:link><br>
        </sec:ifLoggedIn>
        <hr>
    %{-- IF Login as admin --}%
        <sec:ifAllGranted roles="ROLE_ADMIN">
    %{--    User CMS Link || Product CMS Link --}%
            <g:link controller='adminUser' action='index'>User CMS</g:link><br>
            <g:link controller='adminRole' action='index'>Role CMS</g:link><br>
            <g:link controller='adminProduct' action='index'>Product CMS</g:link>
            <hr>
        </sec:ifAllGranted>
        <h1>Browse Products</h1>
        <g:link action="create">[+] Create</g:link>
        <p>${error}</p>

        <g:each in="${products}" var="product" status="i">
            <h3>${i+1}.) <g:link action="show" params="[id: product.id]">${product.name}</g:link></h3>
        %{-- IF current_user == added_by --}%
        %{--    Display "Added by you" --}%
            <p><i>Sale Date : ${product.saleDate} // Added By ${product.addedBy}</i></p>
            <h3>THB ${product.salePrice}</h3>
            <br><hr>
        </g:each>
    </body>
</html>

grails-app/views/home/invalid.gsp
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>Product not found | Simple Online Store</title>
    </head>

    <body>
        <h1>This product is invalid or not available at this time.</h1>
        <g:link action="index" controller="home">< Back</g:link>
    </body>
</html>

grails-app/views/home/show.gsp
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>${product?.name} | Simple Online Store</title>
    </head>

    <body>
        <h1>${product?.name}</h1>
        <h3>THB ${product?.salePrice}</h3>
    %{-- IF current_user == added_by --}%
        <hr>
    %{-- IF current_user == added_by --}%
    %{--    Display "Added by you" --}%
        <p><i>Sales Date: ${product?.saleDate} // Added By: ${product?.addedBy}</i></p>
        <br>
        <p>${product?.description}</p>
        <br>
        <g:link action="index" controller="home">< Back</g:link>
    </body>
</html>