grails-app/controllers/mystore/AdminRoleController.groovy
package mystore

import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN'])
class AdminRoleController {

    def adminRoleService
    static def allowedMethods = [store: "POST"]

    def index() {
        render(view: "index", model: [roles: Role.findAll()])
    }

    def create() {
        render(view: "create", model: [role: new Role()])
}

    def store(Role role) {
        withForm {
            def error = adminRoleService.saveRole(role)
            if (error == "")
                redirect(action: "index")
            else
                render(view: "create", model: [error: error])
        }.invalidToken {
            render(view: "index", model: [error: "ERROR : Invalid Token !"])
        }
    }
}

grails-app/controllers/mystore/AdminUserController.groovy
package mystore

import grails.plugin.springsecurity.annotation.Secured
import mystore.User

@Secured(['ROLE_ADMIN'])
class AdminUserController {

    def adminUserService
    static def allowedMethods = [store: "POST", update: "POST", delete: ["POST", "DELETE"]]

    def index() {
        render(view: "index", model: [users: User.findAll()])
    }

    def create() {
        render(view: "create", model: [user: new User()])
    }

    def store(User user) {
        withForm {
            if(params.password == params.confirmed_password) {
                def status = adminUserService.saveUser(user)
                if (status == "")
                    redirect(action: "index")
                else
                    render(view: "create", model: [error: status])
            } else {
                render(view: "create", model: [error: "ERROR : password != confirmed_password"])
            }
        }.invalidToken {
            render(view: "index", model: [error: "ERROR : Invalid Token !"])
        }
    }

    def show(User user) {
        render(view: "show", model: [user: user])
    }

    def edit(User user) {
        render(view: "edit", model: [user: user])
    }

    def update(User user) {
        withForm {
            if(params.password == params.confirmed_password) {
                def status = adminUserService.saveUser(user)
                if(status == "")
                    redirect(action: "index")
                else
                    render(view: "edit", model: [user: user, error: status])
            } else {
                render(view: "edit", model: [user: user, error: "ERROR : password != confirmed_password"])
            }
        }.invalidToken {
            render(view: "index", model: [error: "ERROR : Invalid Token !"])
        }
    }

    def delete(User user) {

    }

}

grails-app/views/adminUser/create.gsp
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>CMS : Create User</title>
    </head>

    <body>
        <h1>Create User</h1>
        <p>${error}</p>
        <g:form action="store" useToken="true">
            <label name="username">Username:</label>
            <g:textField name="username"></g:textField>
            <br>
            <label name="password">Password:</label>
            <g:passwordField name="password"></g:passwordField>
            <br>
            <label name="confirmed_password">Re-enter Password</label>
            <g:passwordField name="confirmed_password"></g:passwordField>
            <br>
            <g:submitButton name="submit" value="Add User"></g:submitButton>
        </g:form>
    </body>
</html>

grails-app/views/adminUser/edit.gsp
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>CMS : Edit User</title>
    </head>

    <body>
    <h1>Edit User ${user.username}</h1>
    <p>${error}</p>
    <g:form action="update" useToken="true">
        <g:hiddenField name="id" value="${user.id}"></g:hiddenField>
        <label name="username">Username:</label>
        <g:textField name="username" value="${user.username}"></g:textField>
        <br>
        <label name="password">Password:</label>
        <g:passwordField name="password"></g:passwordField>
        <br>
        <label name="confirmed_password">Re-enter Password</label>
        <g:passwordField name="confirmed_password"></g:passwordField>
        <br>
        <g:submitButton name="submit" value="Add User"></g:submitButton>
    </g:form>
    </body>
</html>

grails-app/views/adminUser/index.gsp
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>CMS : User List</title>
    </head>

    <body>
        <h1>CMS : User List</h1>
        <g:link action="create">[+] Add User</g:link>
        <g:link action="index" controller="adminRole">Manage Role ></g:link>
        <table>
            <th>
            <td>Username</td>
            <td>User Detail</td>
        </th>
            <g:each in="${users}" var="user" status="i">
                <tr>
                    <td>${i+1}</td>
                    <td>${user.username}</td>
                    <td>
                        <g:link action="show" params="[id: user.id]">Show ></g:link>
                        <g:link action="edit" params="[id: user.id]">Edit ></g:link>
                    </td>
                </tr>
            </g:each>
        </table>
    </body>
</html>

grails-app/views/adminUser/show.gsp
<!DOCTYPE HTML>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>CMS : ${user?.username}</title>
    </head>

    <body>
        <h1>User Detail</h1>
        <hr>
        <g:link action="edit">[-] Edit</g:link>
        <p><b>Username:</b> ${user?.username}</p>
        <p><b>Password:</b> ${user?.password}</p>
        <g:link action="index">< Back</g:link>
    </body>
</html>